#!/bin/bash

function PrintHelp () {
	echo "Usage : gt [path]"
    echo "  or:   gt -d "
    echo "  or:   gt -h"
    echo -e "\n\t-d\tdebug mode"
    echo -e "\t-h\tdisplay this help and exit"
	exit 0
}

function Error () {
	echo "Error - Syntax invalid. --help or -h for help"
	exit "$1"	
}

#echo for debug
function echod () {
	if [ "$Debug" = "True" ]
	then
		echo "$*"
	fi
}

# Check args
function CheckArgs () {
	case $1 in
		--help|-h)
			PrintHelp
			;;
		-d)
			Debug="True"
			return 1
			;;
	esac
	return 0
}

#CheckHome:
#check if we are in $HOME or not
#return :
# -> 0 if yes
# -> 1 not
function CheckHome () {
	echod "CheckHome"
	case $PWD in
		"$HOME"*)
			return 0
			;;
		*)
			return 1
			;;
	esac
}

#CheckPath:
#Verify conditions for execute script:
# - if "cd" -> go home
# - if "/" (root) -> don't execute script
# - if "cd .." | "cd ./" (aka specials comands) -> don't execute script
function CheckPath () {
	echod "CheckPath"
	if [ "$Path" = "" ]
	then
		echo "$HOME"
		exit 0
	fi
	CheckHome
	if [ $? -eq 1 ]
	then
		echo "$Path"
		exit 0
	fi
	case $Path in
		".."*|"./"*|"/"*|"-")
			echo "$Path"
			exit 0
			;;
	esac
}

#FormatPath:
#Remove the last "/" if contain last "/"
#Return: $PathFormatted
function FormatPath () {
	echod "FormatPath"
	if [ "${Path:${#Path}-1:1}" = "/" ]
	then
		PathFormatted=$(echo "$Path" | sed 's/.$//')
		#PathFormatted=${$Path//.$//}
		#${variable//search/replace}
	else
		PathFormatted="$Path"
	fi
	echod "Formatted path: $PathFormatted"
}

#research directory $Path
function CreateList () {
	ListDir=$(find "$PWD" -mindepth 1 -maxdepth 4 -type d \( -name '.*' -prune -o -print \) | grep -i "$PathFormatted")

	#echod "$ListDir"

	if [ "$ListDir" = "" ]
	then
		echod "List empty"
		exit 0
	fi
}

function FindDirectory () {
	declare -i Position=0
	declare -i PositionDir=0

	#save IFS
	OldIFS=$IFS
	IFS=$'\n'

	Arr=($ListDir)
	FirstElement=${Arr[0]}
	Length=$((${#FirstElement}+1))
	
	echod "$FirstElement  $Length"
	echod "------------------"

	for Dir in $ListDir
	do
		Position=$((Position + 1))
		echod "$Position  - ${#Dir} - $Dir"
		LengthDir=${#Dir}
		if [ "$LengthDir" -lt $Length ]
		then
			echod "$LengthDir < $Length" 
			Length=$LengthDir
			PositionDir=$Position
		fi
	done
	#restore IFS
	IFS=$OldIFS

	#Final=$(echo "${Arr[$PositionDir-1]}" | sed 's/ /\\ /g')
	PathFinal="${Arr[$PositionDir-1]}"
	echod "Final path : $PathFinal"
}

## ---- Main program ----

# Variables declarations
Debug="False"
Path=""
PathFormatted=""
PathFinal=""
ListDir=""

CheckArgs "$1"
if [ $? -eq 1 ]
then
	echod "Shift"
	shift
fi

Path="$*"
echod "Path: $Path"

CheckPath
FormatPath 
CreateList

FindDirectory

echo "$PathFinal"

